import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
          charSet="utf-8"
        />
        <script src="/tinymce/plugins/mathjax/config-unicode.js"></script>
        <script src="/tinymce/plugins/mathjax/tex-mml-chtml.js"></script>
      </head>
      <body>{children}</body>
    </html>
  );
}
